services:
    wardormeur.phpbbwpunicorn.user:
        class: wardormeur\phpbbwpunicorn\user
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @user
            - @user_loader
            - %core.php_ext%
            - %core.root_path%    
    wardormeur.phpbbwpunicorn.proxy:
        class: wardormeur\phpbbwpunicorn\proxy
        calls:
            - [set_config,[@config]]
            - [set_phpEx, ["%core.php_ext%"]]
            - [set_phpbb_root_path, ["%core.root_path%"]]


    wardormeur.phpbbwpunicorn.listener:
        class: wardormeur\phpbbwpunicorn\event\createuser_listener
        arguments:
            - @template
            - @user
            - @dbal.conn
            - @auth
            - @request
            - @cache.driver
            - @wardormeur.phpbbwpunicorn.user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
